
server:
  port: 5000 # beanstalk default port

spring:
  data:
    mongodb:
      uri: ${DB_URI:}


telegram:
  botToken: ${telegram_token:}
  botName: ${telegram_bot_name:}


stripe:
  api:
    secretKey: ${stripe_sk}
    publicKey: ${stripe_pk}
    stripeEndpointSecretWebhook: ${websocket-stripe-secret:}

  